# pyright: reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false
"""A scripted chat model for running the app without an API key.

Enabled with ``S2C_FAKE_MODEL=1``. It emulates what a real model does through
the deep agent: it streams a short "thinking" delta, streams a ``create_file``
(or, for update requests, an ``edit_file``) tool call argument-by-argument, and
after the tool result it replies with a one-sentence summary.
"""

import json
from typing import Any, AsyncIterator, Iterator, Optional

from langchain_core.callbacks import AsyncCallbackManagerForLLMRun, CallbackManagerForLLMRun
from langchain_core.language_models import BaseChatModel
from langchain_core.messages import AIMessage, AIMessageChunk, BaseMessage, HumanMessage, ToolMessage
from langchain_core.outputs import ChatGeneration, ChatGenerationChunk, ChatResult

FAKE_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Fake model output</title>
<script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-50 text-slate-900">
<main class="mx-auto max-w-3xl p-8">
  <h1 class="text-3xl font-bold">Generated by the scripted fake model</h1>
  <p class="mt-4 text-slate-600">Set OPENROUTER_API_KEY and unset S2C_FAKE_MODEL to generate real code.</p>
  <button class="mt-6 rounded bg-indigo-600 px-4 py-2 text-white">Primary action</button>
</main>
</body>
</html>"""


def _last_human_text(messages: list[BaseMessage]) -> str:
    for message in reversed(messages):
        if isinstance(message, HumanMessage):
            content = message.content
            if isinstance(content, str):
                return content
            return " ".join(
                str(part.get("text", "")) for part in content if isinstance(part, dict)
            )
    return ""


class ScriptedCodegenModel(BaseChatModel):
    """Deterministic stand-in for an OpenRouter model."""

    chunk_size: int = 48
    bound_tools: list[Optional[str]] = []

    @property
    def _llm_type(self) -> str:
        return "scripted-codegen"

    def bind_tools(self, tools: Any, **kwargs: Any) -> "ScriptedCodegenModel":  # type: ignore[override]
        self.bound_tools = [
            getattr(t, "name", None) or (t.get("name") if isinstance(t, dict) else None) for t in tools
        ]
        return self

    def _get_ls_params(self, stop: Optional[list[str]] = None, **kwargs: Any) -> Any:
        params = super()._get_ls_params(stop=stop, **kwargs)
        params["ls_provider"] = "openrouter"
        return params

    # ----------------------------------------------------------- scripting

    def _plan_turn(self, messages: list[BaseMessage]) -> list[AIMessageChunk]:
        tool_results = [m for m in messages if isinstance(m, ToolMessage)]
        if tool_results:
            # After writing the file, look at it once if the preview tool exists
            # (exercises the multimodal tool-result path), then wrap up.
            used = {m.name for m in tool_results}
            if "screenshot_preview" in self.bound_tools and "screenshot_preview" not in used:
                return [
                    AIMessageChunk(
                        content="",
                        tool_call_chunks=[
                            {"name": "screenshot_preview", "args": "{}", "id": "call_fake_2", "index": 0}
                        ],
                    )
                ]
            return [AIMessageChunk(content="Built the page with the scripted fake model.")]

        is_update = "<current_file" in _last_human_text(messages) or any(
            isinstance(m, AIMessage) and "<file " in str(m.content) for m in messages
        )
        if is_update:
            args = json.dumps(
                {
                    "path": "index.html",
                    "old_text": "<title>",
                    "new_text": "<title>Updated: ",
                    "count": 1,
                }
            )
            name = "edit_file"
        else:
            args = json.dumps({"path": "index.html", "content": FAKE_HTML})
            name = "create_file"

        chunks: list[AIMessageChunk] = [
            AIMessageChunk(
                content="",
                additional_kwargs={"reasoning_content": "Planning the layout from the input."},
            )
        ]
        first = True
        for start in range(0, len(args), self.chunk_size):
            piece = args[start : start + self.chunk_size]
            chunks.append(
                AIMessageChunk(
                    content="",
                    tool_call_chunks=[
                        {
                            "name": name if first else None,
                            "args": piece,
                            "id": "call_fake_1" if first else None,
                            "index": 0,
                        }
                    ],
                )
            )
            first = False
        return chunks

    # ------------------------------------------------------------ interface

    def _generate(
        self,
        messages: list[BaseMessage],
        stop: Optional[list[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> ChatResult:
        chunks = self._plan_turn(messages)
        merged: Optional[AIMessageChunk] = None
        for chunk in chunks:
            merged = chunk if merged is None else merged + chunk
        assert merged is not None
        message = AIMessage(
            content=merged.content,
            tool_calls=merged.tool_calls,
            additional_kwargs=merged.additional_kwargs,
        )
        return ChatResult(generations=[ChatGeneration(message=message)])

    def _stream(
        self,
        messages: list[BaseMessage],
        stop: Optional[list[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> Iterator[ChatGenerationChunk]:
        for chunk in self._plan_turn(messages):
            yield ChatGenerationChunk(message=chunk)

    async def _astream(
        self,
        messages: list[BaseMessage],
        stop: Optional[list[str]] = None,
        run_manager: Optional[AsyncCallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> AsyncIterator[ChatGenerationChunk]:
        for chunk in self._plan_turn(messages):
            yield ChatGenerationChunk(message=chunk)
